# Generated by Django 4.2 on 2023-05-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_eventofijo_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
