# Generated by Django 4.2 on 2023-05-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_meta_dias_estimados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='dias_estimados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
