# Generated by Django 5.1.1 on 2024-10-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_meta_dias_estimados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='usuario',
        ),
    ]
